import type { EarnProductsType, UserData } from "~/utils/types";

export const MOBILE_WIDTH: number = 800; // px

export const ORDERBOOK_LEVELS: number = 6; // rows count

export const SERVER_URL = "150.95.26.212:22";
export const LOCAL_URL = "https://api.auno.site";

export const API_URL = "https://www.auno.site";

export const TitleSuffix = "Binance";
export const ACTION_URL = "http://150.95.82.150:4000";

export const walletTypes = [
  {type:"financial"},
  {type:"funding"},
  {type:"spot"}
]
export const user: UserData = {
  UserName: "Samuel Chost",
  Email: "samuelchost@gmail.com",
  PasswordHash: "samuellll",
  Phone: "",
  KycStatus: "verified",
  AccountLevel: "basic",
  InvitationCode: null,
  CreatedAt: "",
  UpdatedAt: "",
  Id: 92002,
  UserWallet: [
    {
      Id: 1,
      UserId: 92002,
      WalletType: "financial",
      Status: "active",
      CreatedAt: "",
      UpdatedAt: "",
      UserAsset: [
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "10002",
          LockedBalance: "0",
          Currency: "USDT",
          CreatedAt: "",
          UpdatedAt: "",
        },
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "1.2",
          LockedBalance: "0",
          Currency: "BTC",
          CreatedAt: "",
          UpdatedAt: "",
        },
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "2.0121",
          LockedBalance: "0",
          Currency: "ETH",
          CreatedAt: "",
          UpdatedAt: "",
        },
      ],
    },
    {
      Id: 2,
      UserId: 92002,
      WalletType: "spot",
      Status: "active",
      CreatedAt: "",
      UpdatedAt: "",
      UserAsset: [
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "499",
          LockedBalance: "0",
          Currency: "USDT",
          CreatedAt: "",
          UpdatedAt: "",
        },
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "0.0023",
          LockedBalance: "0",
          Currency: "BTC",
          CreatedAt: "",
          UpdatedAt: "",
        },
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "1",
          LockedBalance: "0",
          Currency: "ETH",
          CreatedAt: "",
          UpdatedAt: "",
        },
      ],
    },
    {
      Id: 3,
      UserId: 92002,
      WalletType: "funding",
      Status: "active",
      CreatedAt: "",
      UpdatedAt: "",
      UserAsset: [
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "100",
          LockedBalance: "0",
          Currency: "USDT",
          CreatedAt: "",
          UpdatedAt: "",
        },
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "0.000123",
          LockedBalance: "0",
          Currency: "BTC",
          CreatedAt: "",
          UpdatedAt: "",
        },
        {
          Id: 1,
          UserId: 92002,
          UserAccountId: 1,
          AvailableBalance: "0.009021",
          LockedBalance: "0",
          Currency: "ETH",
          CreatedAt: "",
          UpdatedAt: "",
        },
      ],
    },
  ],
};

export const EarnProductTest: EarnProductsType[] = [
  {
    Id: 1,
    Name: "ETH",
    MinApr: 2.12,
    MaxApr: 9.56,
    DurationDays: 0,
    MinAmount: "1",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: true,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 2,
    Name: "BTC",
    MinApr: 5.56,
    MaxApr: 8.34,
    DurationDays: 0,
    MinAmount: "100",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: true,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 3,
    Name: "ADA",
    MinApr: 3.67,
    MaxApr: 7.26,
    DurationDays: 0,
    MinAmount: "10",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: true,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id:4,
    Name: "USDT",
    MinApr: 3.86,
    MaxApr: 8.34,
    DurationDays: 0,
    MinAmount: "1",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: true,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 5,
    Name: "USDC",
    MinApr: 2.9,
    MaxApr: 6.35,
    DurationDays: 0,
    MinAmount: "1",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: true,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id:6,
    Name: "XRP",
    MinApr: 4.45,
    MaxApr: 9.93,
    DurationDays: 0,
    MinAmount: "10",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: true,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id:7,
    Name: "ETH-BTC",
    MinApr: 9.26,
    MaxApr: 18.94,
    DurationDays: 30,
    MinAmount: "1000",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 8,
    Name: "ADA-XRP",
    MinApr: 6.98,
    MaxApr: 14.12,
    DurationDays: 30,
    MinAmount: "100",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 9,
    Name: "LTC-BTC",
    MinApr: 7.12,
    MaxApr: 18.93,
    DurationDays: 30,
    MinAmount: "500",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 10,
    Name: "ETC-BTC",
    MinApr: 9.41,
    MaxApr: 17.52,
    DurationDays: 60,
    MinAmount: "500",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 11,
    Name: "DOGE-BTC",
    MinApr: 8.54,
    MaxApr: 15.12,
    DurationDays: 60,
    MinAmount: "500",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 12,
    Name: "SOL-ETH",
    MinApr: 8.98,
    MaxApr: 18.44,
    DurationDays: 60,
    MinAmount: "1000",
    MaxAmount: "1000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 13,
    Name: "AVAX-BTC",
    MinApr: 11.41,
    MaxApr: 19.82,
    DurationDays: 90,
    MinAmount: "1000",
    MaxAmount: "5000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 14,
    Name: "LINK-BTC",
    MinApr: 12.34,
    MaxApr: 21.47,
    DurationDays: 90,
    MinAmount: "1000",
    MaxAmount: "5000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
  {
    Id: 15,
    Name: "ATOM-ETH",
    MinApr: 10.01,
    MaxApr: 22.95,
    DurationDays: 90,
    MinAmount: "1000",
    MaxAmount: "5000000",
    RiskLevel: "",
    IsFlexible: false,
    isActive: true,
    CreatedAt: "",
    UpdatedAt: "",
  },
];
